
export const PAYSTACK_URL = 'PAYSTACK_URL';
export const PAYSTACK_SECRET_KEY = 'PAYSTACK_SECRET_KEY';
export const PAYSTACK_USE_WEBHOOK = 'PAYSTACK_USE_WEBHOOK';

export const PAYSTACK_WEBHOOK_HANDLER = Symbol('PAYSTACK_WEBHOOK_HANDLER');
export const PAYSTACK_WEBHOOK_SERVICE = Symbol('PAYSTACK_WEBHOOK_SERVICE');
export const PAYSTACK_CONFIG_MODULE_OPTIONS = Symbol('PAYSTACK_CONFIG_MODULE_OPTIONS');
